# This GitHub Actions composite action is designed to install Playwright and its dependencies,
# utilizing caching to speed up subsequent runs. It determines the Playwright version,
# checks for a cached version, installs Playwright and its dependencies if not cached,
# and installs only the dependencies if cached.

name: Install Playwright
description: Install Playwright and dependencies with cache

# Inputs define parameters for the action, such as the working directory and browsers to install.
inputs:
    working-directory:
        description: Where to install Playwright
        default: ${{ github.workspace }}
    browsers:
        description: Browsers to install
        default: chromium webkit firefox

# Outputs provide information about the installed Playwright version and cache status.
outputs:
    version:
        description: Installed version of Playwright
        value: ${{ steps.version.outputs.version }}
    cache-hit:
        description: Whether cache for Playwright was found
        value: ${{ steps.cache.outputs.cache-hit }}

runs:
    using: composite
    steps:
        # Determines the Playwright version by reading the package.json file.
        - name: Get Playwright version
          uses: actions/github-script@v7
          id: version
          with:
              script: |
                  // Sets the working directory based on input.
                  const workingDirectory = "${{ inputs.working-directory }}";
                  console.debug("Specified working directory:", workingDirectory);
                  if (workingDirectory) process.chdir(workingDirectory);
                  console.debug("Actual working directory:", process.cwd());
                  let version = "";
                  try {
                    // Attempts to read the Playwright version from package.json.
                    version = require("@playwright/test/package.json").version;
                  } catch (error) {
                    console.log(error.message);
                  }
                  console.debug("Version:", version);
                  if (version) {
                    // Exports the version as an environment variable and output.
                    core.exportVariable("PLAYWRIGHT_VERSION", version);
                    core.setOutput("version", version);
                  } else core.setFailed("Couldn't get Playwright version");

        # Caches the Playwright installation to speed up future runs.
        - name: Cache Playwright
          id: cache
          uses: actions/cache@v4
          with:
              # path: ${{ inputs.working-directory }}
              path: | 
                ${{ inputs.working-directory }}
                /home/runner/.cache
              # key: playwright-${{ env.PLAYWRIGHT_VERSION }}
              key: ms-playwright

        # Installs Playwright and its dependencies if the cache is not found.
        - name: Install Playwright and its dependencies
          shell: bash
          if: steps.cache.outputs.cache-hit != 'true'
          working-directory: ${{ inputs.working-directory }}
          run: npx playwright install ${{ inputs.browsers }} --with-deps

        # Installs only Playwright's dependencies if the cache is found.
        - name: Install just Playwright's dependencies
          shell: bash
          if: steps.cache.outputs.cache-hit == 'true'
          working-directory: ${{ inputs.working-directory }}
          run: yarn playwright install && npx playwright install-deps
