name: Update Snapshots on Comment

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  issue_comment:
    types: [created]

jobs:
  update-snapshots:
    name: Update Snapshots

    if: github.event.issue.pull_request && contains(github.event.comment.body, '/approve-snapshots')
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest

    permissions:
      # Required for stefanzweifel/git-auto-commit-action@v5
      # so that it can commit and push the added or changed
      # files to the repository.
      contents: write
      # Required for thollander/actions-comment-pull-request@v3
      # https://github.com/thollander/actions-comment-pull-request?tab=readme-ov-file#permissions
      pull-requests: write
      issues: write

    steps:
      - name: Get branch of PR
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          persist-credentials: false

      - name: Check Cache for Playwright
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}

      # Set up SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git status
      - name: Check git fetch
        run: |
          git remote -v
          # git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          git fetch
          git status

      - name: Comment action started
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ### Updating snapshots. Click [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) to see the status.
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn
            yarn.lock
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installing Yarn and setting env
        run: |
          npm install -g pnpm
          npm config set "@broadlume:registry" "https://npm.pkg.github.com"
          npm config set "//npm.pkg.github.com/:_authToken" "${{ secrets.NPM_TOKEN }}"
          git status

      - name: Install dependencies
        run: pnpm

      # - name: Install Playwright
      #   id: install-playwright
      #   uses: ./.github/actions/install-playwright

      - name: Install Playwright
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run Playwright tests
        run: |
          git status
          yarn test --update-snapshots
          git status

      - name: Commit and push updated snapshots
        run: |
          git status
          git config --global user.name TirthS24
          git config --global user.email tirths@york.ie
          git remote set-url origin git@github.com:${{ github.repository }}
          git rev-parse --abbrev-ref HEAD
          git rev-parse HEAD
          git status
          git fetch
          git pull
          git add .
          git commit -m 'fix: update e2e snapshots' --allow-empty
          git push origin ${{steps.comment-branch.outputs.head_ref}}

      - name: Comment success
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ### 🎉 Successfully updated and committed Playwright snapshots! 🎉
